### ISSUE TITLE
[Windows] NCPA 3.1.0 to NCPA 3.1.1 - ncpa.exe will not run

### ISSUE THREAD

**Issue by Mojo-OG** [NagiosEnterprises/ncpa#1210]
Upgrading in-place from 3.1.0 to 3.1.1 on Windows Server 2019 and Windows Server 2022 results in this message being thrown (also prevents the service from starting).
![image](https://github.com/user-attachments/assets/7e6260ae-3864-4854-98e2-5591a9191e44)

**Comment by sawft99** [comment]
Didn't have issues with Server 2019 Standard on mine. Just ran the normal exe. I seem to recall sometimes having issues with those services not stopping correctly or something along those lines when I did other upgrades. Maybe try stopping them and then running the upgrade and see if that works

**Comment by markbevill811** [comment]
We had an issue with the upgrade not running because of a file being locked. The only work around we found was to uninstall NCPA, reboot and reinstall.

**Comment by sawft99** [comment]
> We had an issue with the upgrade not running because of a file being locked. The only work around we found was to uninstall NCPA, reboot and reinstall.

I think that lock may have been from the services thing i mentioned.

**Comment by sawft99** [comment]
> > > We had an issue with the upgrade not running because of a file being locked. The only work around we found was to uninstall NCPA, reboot and reinstall.
> > 
> > 
> > I think that lock may have been from the services thing i mentioned.
> 
> Further to this, the application would not uninstall correctly thereafter either. Running the uninstaller would end up removing uninstall.exe and nothing else. All other files except for .\lib\servicemanager.pyd could be manually deleted, as servicemanager.pyd was reportedly locked by Windows Event Log.
> 
> A reboot was not feasible on most machines. Instead I used procexp.exe to find the offending svchost.exe processes locking servicemanager.pyd, killed them, and was able to then both remove the locked file and also cleanly uninstall NCPA on other machines I had not yet attempted uninstall on. This ultimately fixed the issue and allowed the service to run correctly after reinstall, but is frustrating because it seems like the Nagios team did not even test this.

I'd ask again if you tried stopping the services before uninstalling on problem machines. This also does not seem to be a problem for everyone since I was able to do in place upgrades with no issues so far. That includes any extra steps like the ones I mentioned.

**Comment by ne-bbahn** [comment]
Has anyone seen anything related to this in their NCPA logs or Windows event logs?

**Comment by Mojo-OG** [comment]
> I'd ask again if you tried stopping the services before uninstalling on problem machines. This also does not seem to be a problem for everyone since I was able to do in place upgrades with no issues so far. That includes any extra steps like the ones I mentioned.

The updates for this application were being handled by PatchMyPC, integrated with SCCM. Conflicting program executables (like ncpa.exe) are configured to be stopped, but only if the installer returns the appropriate response codes that would indicate the installer/upgrader could not be completed due to a running service that conflicts.

**Comment by BitKeeper82** [comment]
Having the same issue. Also installing via PatchMyPC (PMPC), integrated with SCCM/Intune. Tested using the PMPC package and with the installers directly. Can confirm it is a file locking issue with Event Viewer. 

VM with v3.1.0 installed.
1. Snapshot VM.
2. Run the v3.1.0 installer with silent switches.
3. Installer finishes without error.
4. **Nagios Cross-Platform Agent** service does not start. 
5. - - - Revert snapshot - - -
6. Stop **Windows Event Log service**
7. Run the v3.1.0 installer with silent switches.
8. Start the **Windows Event Log service**
9. **Nagios Cross-Platform Agent** service now starts.

Can reproduce the same issue every time.

**Comment by ne-bbahn** [comment]
@BitKeeper82, Thank you for figuring out what is going wrong. I can't devote any time to this for the next month, but I will investigate and get this solved as soon as I can.

**Comment by sistemmsn** [comment]
Your version of NCPA fails me on more than 200 servers, do you know what that means? Do you know the impact this problem has on me, if you tested the new version? I'm still with my team downloading the NCPA versions and getting rid of errors, do you have fixes to solve it? oh who is complaining we have hired nagios XI Bussines

**Comment by sistemmsn** [comment]
I can't uninstall it because it literally dies, it won't let me reinstall anymore, my only solution is to reinstall over the existing one in its version 3.1.0 and ignore the error
![image](https://github.com/user-attachments/assets/ac2bcd79-565a-4095-a8a1-c101f9cbb486)

**Comment by ne-bbahn** [comment]
@sistemmsn, Have you checked the NCPA logs or the Windows Event logs to try and figure out what is going wrong? What versions of Windows are you encountering this on? I haven't had any issues installing or upgrading NCPA on my machines.

**Comment by sistemmsn** [comment]
@ne-bbahn windows server 2019 and 2022, I reinstalled version 3.1.1 server 2019 again, but I had to remove the entire NCPA (3.1.0), it seems that the problem is derived from version 3.1.0, because I installed version 3.1.1 on another new one and it worked, for it to work correctly you must uninstall version 3.1.0 and install 3.1.1 and then it works.

**Comment by Matty-uk** [comment]
I did 50 to 60 Windows 2019/2022 NCPA 3.1.0 to NCPA 3.1.1 upgrades via silent install the Friday after 3.1.1 was released.  For me every single one worked without a problem.

**Comment by sawft99** [comment]
I actually have this happening on most of mine too now. I don't know why. I had this happen a few versions ago too. I'm trying to think of what may be special about my environment. This is the only thing i can think off:

- WSUS
- Crowdstrike
- Datto Agent

**Comment by fdeyso** [comment]
> @sistemmsn, Have you checked the NCPA logs or the Windows Event logs to try and figure out what is going wrong? What versions of Windows are you encountering this on? I haven't had any issues installing or upgrading NCPA on my machines.

Hi
we have the same issue on most of our production servers, for some reason on test servers that we only use to validate backups and they have no services apart from the really basic ones it updated just fine.
The only thing I can see in the logs is that the service didn't start. For now I redeployed 3.1.0 but I'd appreciate some help.
![image](https://github.com/user-attachments/assets/c2f5928f-d9a4-4827-b9f1-ddeaec28c234)
![image](https://github.com/user-attachments/assets/6ca90ee5-5819-4201-b123-9d7cafd560df)
![image](https://github.com/user-attachments/assets/1d090464-440f-4775-9950-ef3a333ea82c)

![image](https://github.com/user-attachments/assets/166bf1e9-eef3-4747-8bcf-a0998f0c590a)

**Comment by ne-bbahn** [comment]
Thanks for the extra data. I can't investigate this for a couple more weeks, but this will be my first priority once I can start working on it. It seems to me that some of the issues are caused by the Python version upgrade (3.11 => 3.12). If you remove Python 3.11, that may resolve that particular issue. I will try to figure out what the sources of all these issues are and if they are related or not.

**Comment by fdeyso** [comment]
> Thanks for the extra data. I can't investigate this for a couple more weeks, but this will be my first priority once I can start working on it. It seems to me that some of the issues are caused by the Python version upgrade (3.11 => 3.12). If you remove Python 3.11, that may resolve that particular issue. I will try to figure out what the sources of all these issues are and if they are related or not.

I'm not sure how I can uninstall just the Python packaged in the application. 
Tried unistalling 3.1.0 and do a clean install of 3.1.1, but didn't help. The uninstaller of 3.1.1 is also broken (I guess it gets hang up on the same libraries), but deploying the 3.1.0 installer over the broken version works and it downgrades just fine (except it deletes all items from the plugins folder and they have to be added back manually)

**Comment by bramassendorp** [comment]
> I can't investigate this for a couple more weeks

Seems like a big issue, that should have high prio now, we have multiple machines affected by this, and simply reinstalling the older version does not solve it. 

I would expect some more "enterprise graded" support on this.

**Comment by jvandermeulen** [comment]
Thanks for adding **Priority** label for this, we actively reached out to our customers to prevent them from upgrading to 3.1.1. on Windows.

**Comment by HCR3333** [comment]
Yeah we have experienced this as well...as noted scripted it to run uninstall and stop Windows event log and then install.   Seems to go ok unless you have vmware then somehow it interrupts communication to the vmware servers.  Still looking into that one.

**Comment by bramassendorp** [comment]
Any solution for this now, it's causing lots of issues as we have automated patch management.

**Comment by ne-bbahn** [comment]
> I can't uninstall it because it literally dies, it won't let me reinstall anymore, my only solution is to reinstall over the existing one in its version 3.1.0 and ignore the error ![image](https://private-user-images.githubusercontent.com/38023703/372177119-ac2bcd79-565a-4095-a8a1-c101f9cbb486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzE4ODIsIm5iZiI6MTczMzMzMTU4MiwicGF0aCI6Ii8zODAyMzcwMy8zNzIxNzcxMTktYWMyYmNkNzktNTY1YS00MDk1LWE4YTEtYzEwMWY5Y2JiNDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE2NTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyODNhNzJjODcwODk2YmUyZTcxMzIzZWM5MzVmNWM1MjY0NzNhMGQ2NzhjOTRkMGJmM2JlZWQ3YmY4YmFlYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mHIQc44KhnDfyFcFEaT02mEhU9UeCvG0JvJif8HwQ64)

I have been able to replicate this issue by having `Event Viewer` open while installing NCPA. As soon as I closed Event Viewer and selected `retry`, the installation worked fine. I will try to get a fix for this into 3.1.2, so the install doesn't get stuck if the Event Viewer is open.

**Comment by ne-bbahn** [comment]
> > @sistemmsn,
> > @ne-bbahn Have you checked the NCPA logs or the Windows Event logs to try and figure out what is going wrong? What versions of Windows are you encountering this on? I haven't had any issues installing or upgrading NCPA on my machines.
> 
> Hi we have the same issue on most of our production servers, for some reason on test servers that we only use to validate backups and they have no services apart from the really basic ones it updated just fine. The only thing I can see in the logs is that the service didn't start. For now I redeployed 3.1.0 but I'd appreciate some help. ![image](https://private-user-images.githubusercontent.com/46848650/375708982-c2f5928f-d9a4-4827-b9f1-ddeaec28c234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDAxMTIsIm5iZiI6MTczMzMzOTgxMiwicGF0aCI6Ii80Njg0ODY1MC8zNzU3MDg5ODItYzJmNTkyOGYtZDlhNC00ODI3LWI5ZjEtZGRlYWVjMjhjMjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE5MTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNTJjZTMwZTEzOWU2YTRkYWE0NTA3M2E2ZGU4ZjBjNmNhZDFiOWFlNTY1NWFhMDFiOTViMjQyYTNmMTNkMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CVlO-iJnHYLUIsB-SO7LahL11R6bIPNFC9TUNcKwJRU) ![image](https://private-user-images.githubusercontent.com/46848650/375709074-6ca90ee5-5819-4201-b123-9d7cafd560df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDAxMTIsIm5iZiI6MTczMzMzOTgxMiwicGF0aCI6Ii80Njg0ODY1MC8zNzU3MDkwNzQtNmNhOTBlZTUtNTgxOS00MjAxLWIxMjMtOWQ3Y2FmZDU2MGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE5MTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNThjMjNlOWFmNzRiNGY0ODA3Mzk4ZWZlOTQ0Y2ZlZTkyZDY2ZTRiNmNmNWQ4ZWNkYmY5ZTQ5Y2RmYjNhY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L2oegLjGAYjvPZTY0JfRhdfoXZ-wVA_sitvr8stbZYs) ![image](https://private-user-images.githubusercontent.com/46848650/375709140-1d090464-440f-4775-9950-ef3a333ea82c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDAxMTIsIm5iZiI6MTczMzMzOTgxMiwicGF0aCI6Ii80Njg0ODY1MC8zNzU3MDkxNDAtMWQwOTA0NjQtNDQwZi00Nzc1LTk5NTAtZWYzYTMzM2VhODJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE5MTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YzA1Y2VjMDU2NWNhMWU4YTFmYjRlZTkyMzVkZjFmOGQzYWU1ODExZDEyMzg4ZTYxYzJmODJjMzQxNTc5MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yftnDxvMpmkVu7WLpN-OqADAYVKJqBVz17p16eONWm4)
> 
> ![image](https://private-user-images.githubusercontent.com/46848650/375709528-166bf1e9-eef3-4747-8bcf-a0998f0c590a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDAxMTIsIm5iZiI6MTczMzMzOTgxMiwicGF0aCI6Ii80Njg0ODY1MC8zNzU3MDk1MjgtMTY2YmYxZTktZWVmMy00NzQ3LThiY2YtYTA5OThmMGM1OTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE5MTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZjdkZjA3NDIwMDJiMTRhOGY2NmYyMzdlMTAyNjNiZDZiYTkzNWUxN2E5ZGM2M2JkZmZmNDc2NzczNTE1YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hZihFCPb_qOTjfGcqzhPt3-paXlm6I2YpD3ftzsMRQk)
> 
> EDIT: I also just got this error message ![image](https://private-user-images.githubusercontent.com/46848650/375772466-d4750fc3-6551-4a46-a983-19014c6d16d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDAxMTIsIm5iZiI6MTczMzMzOTgxMiwicGF0aCI6Ii80Njg0ODY1MC8zNzU3NzI0NjYtZDQ3NTBmYzMtNjU1MS00YTQ2LWE5ODMtMTkwMTRjNmQxNmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE5MTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiOTE5MzRmOWE4NTFlOTE5YzY3NGZiNmZkYmJlN2YxMzQ3OWQzMDZmYmI1YjRmYWMwNzg2ZTU1NDcxYTVlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A8LyYyHU2HP1FEfz1RoIZABtLxGk4zVtvDATwJ-3q6U)

This is not how you start NCPA. To start NCPA, you run the installer and then from the CLI, run `sc start ncpa` or you can start the NCPA service from the Task Manager or the Services program. Trying to run the NCPA executable directly will result in the error you received.

**Comment by fdeyso** [comment]
I know that probably running the exe is not the best idea to start the service, but starting the service did nothing also.
I think nxlog running is probably related to the issue, following the above recommendations to stop EventLog, update and then restart Eventlog, the ncpa agent starts fine, but then nxlog crashes and has to be started manually.

**Comment by ne-bbahn** [comment]
@fdeyso,
Do you know what you've modified/configured with nxlog? I tried setting up a system with nxlog running and haven't had any issues upgrading NCPA from 3.1.0 to 3.1.1. I tried with both active and silent install.

**Comment by sawft99** [comment]
> > I can't uninstall it because it literally dies, it won't let me reinstall anymore, my only solution is to reinstall over the existing one in its version 3.1.0 and ignore the error ![image](https://private-user-images.githubusercontent.com/38023703/372177119-ac2bcd79-565a-4095-a8a1-c101f9cbb486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzE4ODIsIm5iZiI6MTczMzMzMTU4MiwicGF0aCI6Ii8zODAyMzcwMy8zNzIxNzcxMTktYWMyYmNkNzktNTY1YS00MDk1LWE4YTEtYzEwMWY5Y2JiNDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE2NTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyODNhNzJjODcwODk2YmUyZTcxMzIzZWM5MzVmNWM1MjY0NzNhMGQ2NzhjOTRkMGJmM2JlZWQ3YmY4YmFlYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mHIQc44KhnDfyFcFEaT02mEhU9UeCvG0JvJif8HwQ64)
> 
> I have been able to replicate this issue by having `Event Viewer` open while installing NCPA. As soon as I closed Event Viewer and selected `retry`, the installation worked fine. I will try to get a fix for this into 3.1.2, so the install doesn't get stuck if the Event Viewer is open. In the mean time, try again with Event Viewer closed.

This happens to me on nearly all my servers and i don't have Event Viewer open. Just the service running.

**Comment by ne-bbahn** [comment]
Based on my testing, this should be resolved in 3.1.4

**Comment by ne-bbahn** [comment]
If anyone is still encountering this error, please either re-open this issue or create a new issue with your specific issue.

**Comment by LorisAlbanese** [comment]
Version 3.1.4 still have this issue. It's not simple to upgrade from a preevious version. 
uninstall still fail.  file servicemanager.pyd in lib directory is not cleaned after uninstall ncpa. 
Windows Event Log service can't be stopped.
Please consider this issue to make upgrade procedure easier.

thank you.

**Comment by markbevill811** [comment]
We use NXLog to send Windows event logs to our Nagios Log Server. We found that by stopping the nxlog service the lock on servicemanager.pyd would be release and we could succefully upgrade NCPA.

**Comment by ne-bbahn** [comment]
@markbevill811, I don't think nxlog is the issue. I set up nxlog to send `ncpa_listener.log` and `ncpa_passive.log` to a log server instance and am having no such issues.

**Comment by markbevill811** [comment]
I had about 20 servers that all followed that pattern. Stop nxlog and the install would run. It might not be that specifically or it may be the logs we grabbing via nxlog.


Mark


________________________________

**Comment by zenobia379** [comment]
Hi! I see that this bug has been troubling people for a lot of time now. 

I'm having this same issue in a lot of machines with Windows Server 2022 and NCPA3, the agent will stop reporting in Nagios, showing Connection refused error. Once I try to restart the service, it gives me a timeout error 1053.

In all of the servers with this problem, the ncpa_listener and ncpa_passive logs stopped reporting after March 1st 2026, and in the Application Event Viewer, the error it shows when trying to start the service is Invalid Driver (6).

It only solves after renaming the servicemanager.pyd, moving it to another folder, uninstalling completely NCPA and installing it afterwards.

Do you know if there is any newer version that fixes this bug or any way to fix it without having to do the reinstall thing always?

Thanks!

**Comment by ne-cdietsch** [comment]
Hi @zenobia379, there has been work done in a few of the releases since this issue opened attempting to fix this and similar problems. 

 I would recommend testing the latest NCPA version (v3.3.0) to see if that helps.

**Comment by zenobia379** [comment]
Yeah, I saw that the servers were deployed with the version 3.1.3... I'll try to install the latest version in all of the servers, currently the ones that we changed haven't given any problems.

Thanks for the help!
