### ISSUE TITLE
Passive custom checks not running after first run

### ISSUE THREAD

**Issue by jomann09** [NagiosEnterprises/ncpa#240]
New bug report for #97. The issue is that the plugins directory can no longer be found after the first initial run of the plugin. This causes node-related errors to appear for passive checks.

**Comment by jomann09** [comment]
This looks like an issue with absolute paths and windows. I am working on changing it to determine the correct path via a different method that is use elsewhere in NCPA for determining paths.

**Comment by jomann09** [comment]
Fixed in commit 4bef37ab21d0ac8d17aad66dbc90100ef078f9c2, will test it tomorrow to verify it is working properly.

**Comment by jomann09** [comment]
Tested and can close this with the above fix.

**Comment by xpedeus** [comment]
Jomann09, I still have this issue and I am using the latest build of NCPA from Nagios's website. Is this bug not committed to this build as of yet? Is there any way I can access this build, or how can I commit these changes to that version that I presently have installed?

Thanks!
Jon

**Comment by xpedeus** [comment]
Nevermind! I was able to find NCPA 2.0 by Googling. :)

**Comment by jomann09** [comment]
Oh yes, this is only fixed in 2.0+, since there isn't a full 2.0.0 release yet you're probably downloading the alpha - which will work but know that you'll want to upgrade to the full version once it's released. It should be releasing fairly soon. I only have 2 more things to finish up.

**Comment by xpedeus** [comment]
Thank you! I can say that for my custom command checks that this version seems to work fairly well. I’ll keep an eye out for future updates.


Thanks again!




[cid:image001.jpg@01CEAA4C.6E174BE0]<http://www.xpedeus.com/>

Best regards,

Jon  Caum

**Comment by jomann09** [comment]
Awesome, make sure you also update any check_ncpa.py script that is < 1.0.0 since it won't work with NCPA 2+ otherwise.

**Comment by xpedeus** [comment]
I don't currently use any of those scripts. I'll remember that in the future though!

Best Regards,
Jonathan Caum

Sent from my iPhone. Please excuse my brevity.

On Oct 4, 2016, at 12:02 PM, Jake Omann <notifications@github.com<mailto:notifications@github.com>> wrote:


Awesome, make sure you also update any check_ncpa.py script that is < 1.0.0 since it won't work with NCPA 2+ otherwise.

-
