### ISSUE TITLE
UNKNOWN: Error occurred while running the plugin. Use the verbose flag for more details.

### ISSUE THREAD

**Issue by 17g-guy** [NagiosEnterprises/ncpa#532]
Multiple Windows servers are intermittently returning the state Unknown. This is happening to 'regular' NCPA checks such as CPU, Memory etc as well as plugin (custom script) checks. The frequency is every few minutes a server will report state unknown:

Check example: -t 'token' -P 5693 -M cpu/percent -w 92 -c 96 -q 'aggregate=avg'

UNKNOWN: Error occurred while running the plugin. Use the verbose flag for more details.
long_plugin_output=An error occurred:[Errno 104] Connection reset by peer

ncpa_listener.log:
2019-04-24 13:36:15,773:ERROR:app:Exception on /api/windowscounters/Print Queue(_Total)/Jobs/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 169, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 927, in api
  File "C:\ncpa\agent\listener\windowscounters.py", line 39, in run_check
  File "C:\ncpa\agent\listener\windowscounters.py", line 107, in get_counter_path
IOError: [Errno 9] Bad file descriptor

check_ncpa.py: 1.1.4
NCPA: 2.1.6
Nagios XI: 5.5.11
Nagios/Python: 2.6.6
Server OS: Server 2012R2 (fully patched)

I have disabled Windows Firewall, Turned off AV. Wireshark capture shows a RST, ACK from the remote server to the Nagios Server. I have changed max_connections = None. Increasing check intervals. Increased Nagios compute resource. Nothing has helped the issue.

Note: I changed over from NSClient++ to NCPA and dont remember having this issue with NSClient.

**Comment by yderi** [comment]
Experiencing the same issue from time to time. Playing with a timeout parameter for ncpa_check.py and for NCPA agent itself doesn't help

**Comment by jomann09** [comment]
The counter path issue should be fixed in 2.1.7 but for the connection problem, the issue I'm having is I am unable to reproduce it on my Windows Server test systems. It's definitely related to the Windows version of NCPA but I am not sure if it's the Windows configuration, Python version, gevent version, or what. I'm thinking about building a Python 3 version to test that this isn't a Python issue.

**Comment by jomann09** [comment]
Closing this as this particular error is fixed in 2.1.7 and other errors with counters is being worked on in #539

**Comment by 17g-guy** [comment]
Hi Jomann09

I have upgraded all NCPA clients to 2.1.8 and am still getting a huge number of "State Unknowns" on my Windows servers :

"UNKNOWN: Error occurred while running the plugin. Use the verbose flag for more details."

The issue doesn't appear to be resolved.

**Comment by jomann09** [comment]
The only thing that was resolved is properly handling missing counters or counters that did not return a proper value by not causing issues and sending out an unknown.

The error you're getting is likely the Windows issue where connections are reset randomly. The issue is either related to Windows or the Python version, but not all Windows versions (server seems to be the only one) and installs seems to have the issue but we have internally looked into this for a while now and have not been able to reproduce with our Windows server installs.

**Comment by 17g-guy** [comment]
OK. Whats the official advise on this? Not to use NCPA? I have had 163 "Unknown Status" instances in the last 24 hours. I have tried to be as helpful as possible with Nagios support and provide as much info as possible.

**Comment by jomann09** [comment]
Which counter(s) are you checking that is giving unknowns? Are there any more error messages in the ncpa_listener.log when you enable debug level logging in ncpa.cfg?

Since NCPA is python we rely on the pypiwin32 api to communicate with the windows backend to get counter data. It's a pretty simple process and when NCPA returns an Unknown it's because that API says that it cannot read the counter (it either is no longer available or the counter is somehow negative) but valid counters should always be query-able. Even a counter with a value of 0 will return that value, which makes me think something else is the problem. I have not been able to re-create this with the counters that I have tested on my Windows test boxes so I am not able to dig in deeper.

You have some options to mitigate this for now if only certain counters aren't working. You could wrap the check on the Nagios side it with a simple shell script that would force it to re-check if it came back unknown, or return a different value. Another alternative would also be to use a basic powershell script with as a plugin in NCPA to grab counter data.

**Comment by 17g-guy** [comment]
I have just checked the State History in Nagios for the last week and filtered by State Unknown (978 instances) and have noticed a pattern!!!!!!!!

The issue seems to only be occurring for CPU Usage NCPA checks or custom powershell checks (there are also some state unknowns for .vbs scripts as well). I have quite a few different powershell checks so its not 1 specific powershell script.

Examples for the checks below

CPU
-t 'token' -P 5693 -M cpu/percent -w 92 -c 96 -q 'aggregate=avg'

Powershell scripts
-v -t 'token' -P 5693 -M 'plugins/CheckEX2013DAG.ps1'
-t 'token' -P 5693 -M 'plugins/win_disk_load.ps1' -a "-dl C -ms 5 -rqw 20 -rqc 50"

VBS
-t 'token' -P 5693 -M 'plugins/DFSR.vbs' -a 5000

**Comment by 17g-guy** [comment]
Debug logs

State Unknown for win_disk_load.ps1 ncpa check occured @ [2019-07-26 03:34:22

I cant see any errors in the logs but the logs do show that another powershell check happens at immediately after the first one. Could this have something to do with it?

2019-07-26 03:34:22,816:INFO:handler:10.1.10.5 - - [2019-07-26 03:34:22] "GET /api/plugins/win_disk_load.ps1/-dl/D/-ms/5/-rqw/20/-rqc/50?token=token&check=1 HTTP/1.1" 200 617 6.078000

2019-07-26 03:34:22,895:INFO:handler:10.1.10.5 - - [2019-07-26 03:34:22] "GET /api/plugins/CheckDBActiveMount.ps1/?token=token&check=1 HTTP/1.1" 200 198 5.469000

Having checked more logs and the times of the issue, it does appear it happens when multiple custom script checks happen at the same time.

**Checking this theory with CPU:**

Issue happens @ 07:32:34

2019-07-25 07:32:34,279:INFO:handler:10.1.10.5 - - [2019-07-25 07:32:34] "GET /api/cpu/percent/?token=token&warning=92&critical=96&check=1&aggregate=avg HTTP/1.1" 200 276 0.562000

2019-07-25 07:32:34,326:INFO:handler:10.1.10.5 - - [2019-07-25 07:32:34] "GET /api/plugins/check_all_services.wsf/-exclude%3Asppsvc%2C/RemoteRegistry%2C/Google/Update/Service/%28gupdate%29%2C/IIS/Admin/Service%2C/Microsoft/Deployment/Toolkit/Monitor/Service%2C/SQL/Server/%28MDTEXPRESS%29%2C/Shell/Hardware/Detection%2C/Downloaded/Maps/Manager%2C/KDService%2C/Dell/Data/Vault/Service/API%2C/Dell/Data/Vault/Collector?token=token&check=1 HTTP/1.1" 200 224 0.188000
2019-07-25 07:32:38,029:DEBUG:handler:Initializing WebSocket

**Comment by jomann09** [comment]
I'm sorry I thought the only issue was with Windows counters which is why I closed this previously. The connection reset by peer issue is still being worked on, how many checks total are you running for each NCPA agent? I'm going to try to build NCPA with an updated version of gevent and see if that will fix the connection issue.

That is interesting that the powershell checks are happening at about the same time, I can test this on my side and see if that is locking up the system or causing the connections to fail. That may actually be related to gevent and how it handles the incoming connections while other connections are busy. I'll give you an update later today on this.

**Comment by 17g-guy** [comment]
No probs. 

How can I find out how many checks total for each NCPA? 
What is gevent?

Let me know if there is anything i can test or do

Thanks for re-opening :)

**Comment by jomann09** [comment]
There isn't really a good way to check the exact amount but you can just estimate it based on how many are in Nagios for a single NCPA.

I'll have you test a 2.1.9 beta build with the updated version of gevent once I get it finished. The gevent module is the python module that runs the internal server for the NCPA listener.

**Comment by jomann09** [comment]
Okay I built a new version of NCPA with an updated version of psutil, gevent, greenlet, etc these are all python modules used to gather data and return it. So let's see if this affects anything. I'll continue testing the multiple powershell scripts happening at the same time to see if that is causing any issues.

If you could try installing this and running it on a system that has the issue and let it run for a day or so, https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.1.9.beta.exe

**Comment by 17g-guy** [comment]
Thanks! Installed and will report back

**Comment by 17g-guy** [comment]
checked first thing this morning and the issue is still there with the 2.1.9 beta

**Comment by jomann09** [comment]
Okay thanks for the info, I will get back after I do some more testing on the multiple checks at the same time, these are active checks (sent via check_ncpa.py from the Nagios server) correct?

**Comment by 17g-guy** [comment]
yes that's correct, check_ncpa.py for all NCPA host checks

**Comment by jomann09** [comment]
I have one more build to try, I'm still looking into this but I also made a change to how the requests are handled on the backend that might affect it, should be able to just download and install the new beta https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.1.9.beta.exe

**Comment by 17g-guy** [comment]
Installed and testing. Will report back

**Comment by 17g-guy** [comment]
Same issue. 2019-07-28 10:21:17

2019-07-28 10:21:17,377:DEBUG:handler:Initializing WebSocket
2019-07-28 10:21:17,377:DEBUG:handler:Validating WebSocket request
2019-07-28 10:21:17,408:DEBUG:psapi:Imported windowscounters into the API tree.
2019-07-28 10:21:17,408:DEBUG:psapi:Imported windowslogs into the API tree.

2019-07-28 10:21:17,408:DEBUG:pluginnodes:Running process with command line: `cscript C:\Program Files (x86)\Nagios\NCPA\plugins\check_all_services.wsf -exclude:sppsvc, RemoteRegistry, Google Update Service (gupdate), IIS Admin Service, Microsoft Deployment Toolkit Monitor Service, SQL Server (MDTEXPRESS), Shell Hardware Detection, Downloaded Maps Manager, KDService, Dell Data Vault Service API, Dell Data Vault Collector //NoLogo`
2019-07-28 10:21:17,549:INFO:handler:10.1.10.5 - - [2019-07-28 10:21:17] "GET /api/plugins/win_disk_load.ps1/-dl/C/-ms/5/-rqw/20/-rqc/50?token=token&check=1 HTTP/1.1" 200 619 6.109000

2019-07-28 10:21:17,581:INFO:handler:10.1.10.5 - - [2019-07-28 10:21:17] "GET /api/plugins/check_all_services.wsf/-exclude%3Asppsvc%2C/RemoteRegistry%2C/Google/Update/Service/%28gupdate%29%2C/IIS/Admin/Service%2C/Microsoft/Deployment/Toolkit/Monitor/Service%2C/SQL/Server/%28MDTEXPRESS%29%2C/Shell/Hardware/Detection%2C/Downloaded/Maps/Manager%2C/KDService%2C/Dell/Data/Vault/Service/API%2C/Dell/Data/Vault/Collector?token=token&check=1 HTTP/1.1" 200 224 0.204000

2019-07-28 10:21:17,861:DEBUG:handler:Initializing WebSocket
2019-07-28 10:21:17,861:DEBUG:handler:Validating WebSocket request
2019-07-28 10:21:17,908:DEBUG:psapi:Imported windowscounters into the API tree.
2019-07-28 10:21:17,908:DEBUG:psapi:Imported windowslogs into the API tree.
2019-07-28 10:21:17,908:DEBUG:pluginnodes:Running process with command line: `c:\windows\sysnative\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Unrestricted -File C:\Program Files (x86)\Nagios\NCPA\plugins\NagiosMonitoring_Exchange2013ContentIndexStateHealth.ps1`

**Comment by jomann09** [comment]
I'm having that problem right now while trying to recreate it. At the moment I am just using a script to simulate running check_ncpa.py running multiple times but I might need to try running it from two different scripts at once.

**Comment by 17g-guy** [comment]
Hi jomann. Just wondering if you are having any joy with this?

**Comment by 17g-guy** [comment]
Hi
I am still having the issue with 2.1.9. This is really disappointing and I will probably have to look else where for a reliable monitoring solution now........

**Comment by ericloyd** [comment]
We have many customers using NCPA to monitor a total of over tens of thousands of Windows machines with none of the issues described herein.  While I can offer no solution, I can say that the platform is quite stable across many installations, so it is not impossible that it is something site specific causing the problem. 

We have also converted thousands of checks from NSclient++ to NCPA with no problems other than code conversion details.

**Comment by yderi** [comment]
Please provide the following info:
1. HW configuration of your server (CPU, RAM, free RAM available, average CPU load, HDD, average disk IO load)
2. Script body of "win_disk_load.ps1"
3. Windows version and platform
4. Full ncpa.cfg config file (remove your token and pass before post)
5. How many times over day does it trigger an error? (look at the service history for dedicated service)

**Comment by jomann09** [comment]
With all the above being said, there is definitely an issue with _some_ Windows powershell scripts that causes problems with forward slashes/directories. Normally it's been due to the escaping/quoting/command that NCPA is running, or a combination of all three.

I'd like to get to the bottom of this, I just haven't had time to dig into the plugins that have the issue. If you could give us a copy of the plugin it would be a lot of help.

**Comment by 17g-guy** [comment]
Im not sure if there are multiple issues going on here.....

If I check the check service history of all services for a windows service the majority of State Unknowns are for CPU:
$USER1$/check_ncpa.py -H $HOSTADDRESS$ -t 'token' -P 5693 -M cpu/percent -w 92 -c 96 -q 'aggregate=avg'

and custom scripts: $USER1$/check_ncpa.py -H $HOSTADDRESS$ -t token -P 5693 -M 'plugins/win_disk_load.ps1' -a "-dl C -ms 5 -rqw 20 -rqc 50"

A typical 24 hour period I can have 15+ state unknowns. 

I can provide the information yderi has requested no problem. just let me know the best way to provide this (Send to email, upload somewhere)

**Comment by yderi** [comment]
It seems that you can attach files here.

Some of mine servers (not all of them) have a similar problem when there is a lack of CPU resources (scripts took too much time to respond in a timely manner) Have you been doing a CPU load performance profiling?

You need to figure out what kind of service mostly returns an unknown status.
Have a look at Nagios server log, is there any clues that can point to the problem?

**Comment by jomann09** [comment]
Can you let me know what version of Python you're running on the Nagios XI server that is running the `check_ncpa.py` script?

**Comment by 17g-guy** [comment]
python --version = Python 2.6.6

All endpoint servers are Server 2012R2 fully patched VMs on Dell Hosts in 2 datacentre’s. Various vm specs but plenty of free resources. 

It’s happening anywhere between 3-10 times a day per host

Some examples of scripts and occurrences:

As mentioned, CPU check: $USER1$/check_ncpa.py -H $HOSTADDRESS$ -t 'token' -P 5693 -M cpu/percent -w 92 -c 96 -q 'aggregate=avg'

Check windows for compromise script: https://exchange.nagios.org/directory/Plugins/Security/Check-Windows-for-Indicators-of-Compromise--2D-Via-Event-Logs/details

IOPS Script:
https://exchange.nagios.org/directory/Plugins/Operating-Systems/Windows-NRPE/Check-Microsoft-Windows-Disk-Load/details

Exchange Script:
https://exchange.nagios.org/directory/Plugins/Email-and-Groupware/Microsoft-Exchange/Exchange-2013-Hub-Transport-Queues-Check-(inc-2E-performance-data)/details

Attached is screenshot of Nagios view and ncpa.cfg sample	

[ncpa.txt](https://github.com/NagiosEnterprises/ncpa/files/3688173/ncpa.txt)
<img width="887" alt="State Unknown - View" src="https://user-images.githubusercontent.com/49721353/66166124-4c083080-e62e-11e9-890d-15f6e1f94de0.PNG">

**Comment by jomann09** [comment]
Thanks for the info, with the Unknown happening, I can re-create the connection reset by peer error and I think that is what you're hitting. If you run enough concurrent checks (including plugin checks) it seems to cause the issue.

I have a few more tests to do to get this working but it's related to `gevent` and how it closes the sockets. In version 1.0.2 it works properly, but in gevent 1.1 it changed and we use 1.2.2 so I built a version with that you can try with the old version. From my testing it seems to solve the issue, but  this might cause some other issues (like with websockets) but if this fixes the issue for you also I can use my current way to recreate the issue for a real fix in 2.1.10.

Test version with old gevent: https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.1.10.beta.exe

**Comment by 17g-guy** [comment]
Thanks. I have installed 2.1.10 beta and will monitor and update you accordingly.

**Comment by 17g-guy** [comment]
I haven't seen the issue happen today on 2 servers which I have installed the 2.1.10 beta (Exchange and print server). I would have expected to have seen a couple of instances. I will monitor over the weekend and report back on Monday.

Thanks

**Comment by jomann09** [comment]
Thanks for the update, that's good news. I'm digging into the gevent changes that may have caused the issue in newer versions, but so far it's been dead ends.

**Comment by 17g-guy** [comment]
Further update. No Unknowns all weekend. This has 100% stopped the issue from happening :)

**Comment by ericloyd** [comment]
I knew we could save your Nagios! :-)

**Comment by jomann09** [comment]
That's great news, on Friday night I actually found the issue (I think) and applying the fix to `gevent` I was able to stop it in the newer versions. I've created a GitHub issue for the `gevent` project and hopefully they can explain what is actually happening, why the fix I made works, etc and add the fix into their next update. Until it gets added in though, I will manually fix our `gevent` on our Windows build server so that it is fixed for the actual 2.1.10 release.

**Comment by 17g-guy** [comment]
Great. I will await 2.1.10 for the rest of my servers unless you suggest i install the beta?

**Comment by yderi** [comment]
@17g-guy 
I can confirm that also have an Unknown error, for some of mine windows servers, but it very rare to hit  Hard state of Unknown for service (also for CPU performance counter). Have you tried a newer version of "check_ncpa.py" to use with the Nagios server?

I will also wait for a fix in a newer version of the NCPA agent to test too.

**Comment by jomann09** [comment]
@17g-guy I don't think there is any issues with using the 2.1.10 beta it just has a windows counter change, the gevent module change, and a minor change to the installer. You can upgrade normally from the beta to the 2.1.10 actual release once it is done in the next couple weeks but it probably won't be officially released until closer to the end of October.

@yderi The fix I applied should fix the connection issues no matter the version of the plugin. When I initially looked at the issue I had thought it might be the plugin causing problems but from what I can tell, it should just be the gevent issue that is causing the random unknowns. Unless it's not a "connection reset by peer" error, in which case it's a different problem altogether.

**Comment by 17g-guy** [comment]
Cant tell you how happy it makes me to see this issue gone!

**Comment by jomann09** [comment]
I'm glad it's solved, I haven't received a response from gevent yet, but I will build the 2.1.10 version with the patched file so this will be fixed. It should be released sometime next week.

**Comment by jomann09** [comment]
One more update, this'll be in 2.2.0 which will be the next version now since we have quite a few enhancements going into it.
